from typing import Any

class AhoCorasick:
    def add_word(self, key: str, value: Any) -> None: ...
    def make_automaton(self) -> None: ...
    def iter(self, text: str) -> list[tuple[int, Any]]: ...
